import { Router } from "express";
import courseRouter from "./course.route";
import authRouter from "./auth.route";
import classRouter from "./class.route";
import lessonRouter from "./lesson.route";
import supportRouter from "./support.route";
import recentRouter from "./recentActivity.route";
import subjectRouter from "./subject.route";
import countRouter from "./count.route";
import pastQuestionRouter from "./pastQuestion.route";
import paymentRouter from "./payment.route";
import termRouter from "./term.route";
import dashboardRouter from "./dashboard.route";
import adminRoleRouter from "./adminRole.route";
import schoolRouter from "./school.route";
import thirdPartyRoute from "./thirdParty.route";
import commentRoute from "./comment.route";
import parentRoute from "./parent.route";
import feedRoute from "./feed.route";
import challengeRoute from "./challenge.route";
import coinRoute from "./coin.route";
import requestRoute from "./request.route";
import facultyRoute from "./faculty.route";
import notificationRoute from "./notification.route";

const router = Router();

router.use("/schools", schoolRouter);
router.use("/courses", courseRouter);
router.use("/adminroles", adminRoleRouter);
router.use("/auth", authRouter);
router.use("/recents", recentRouter);
router.use("/counts", countRouter);
router.use("/subjects", subjectRouter);
router.use("/supports", supportRouter);
router.use("/lessons", lessonRouter);
router.use("/classes", classRouter);
router.use("/past-questions", pastQuestionRouter);
router.use("/dashboard", dashboardRouter);
router.use("/terms", termRouter);
router.use("/payments", paymentRouter);
router.use("/thirdParty", thirdPartyRoute);
router.use("/comments", commentRoute);
router.use("/coins", coinRoute);
router.use("/challenges", challengeRoute);
router.use("/feeds", feedRoute);
router.use("/parents", parentRoute);
router.use("/student-requests", requestRoute);
router.use("/faculty", facultyRoute);
router.use("/notifications", notificationRoute);

export default router;
